spring:
    datasource:
        url: jdbc:mysql://localhost:3306/book_store?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
    mail:
        host: localhost
        port: 25
        username:
        password:
server:
    port: 8080

#================================================================
# App specific properties
#================================================================
book-store:
    mail:
        from:
        baseUrl: