spring:
    application:
        name: book-store
    profiles:
        active: dev
    jackson:
        serialization.write_dates_as_timestamps: false
        time-zone: Europe/Skopje
        date-format: yyyy-MM-dd HH:mm:ss
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

#================================================================
# App specific properties
#================================================================
book.store:
    jwt:
        header: Authorization
        secret: BC1428EE0A4FE1F689E5B70D1D6C004ADD76F003FC8B836ABF00166F7A956539
        tokenValidInMinutes: 60
        tokenRefreshableInMinutes: 604800