spring:
    application:
        name: book-store
    profiles:
        active: dev
    jackson:
        serialization.write_dates_as_timestamps: false
        time-zone: Europe/Skopje
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

#================================================================
# App specific properties
#================================================================
book-store:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    jwt:
        secret: BC1428EE0A4FE1F689E5B70D1D6C004ADD76F003FC8B836ABF00166F7A956539
        tokenValidInMinutes: 60
        tokenRefreshableInMinutes: 604800
    payPal:
        clientId: AQs3l1zG8SL-73BefhH-3Vtkdy9K5I9rREfJl-T2cF4w5hJ6xiebLbD09YYp3SdXf1RDij5h_qg4SFzj
        clientSecret: ECwEgRAHk-JZ5aBVwVesD73e1q8gjG1IoB5fY8XnmiPe5NpP1E63pSXADclx5XwR8MlnUPJ0gd-biPjn